### ISSUE TITLE
GetApi().OAuth2.GetAccessToken(code, state) fails

### ISSUE THREAD

**Issue by ltoshev** [SparkleNetworks/LinkedInNET#1]
I am called on this url:

 http://www.cvpanda.com/LinkedIn/Index?code=AQTBkadYVh-JlI0TFeIAZsUToxZBpusyXk4QQFEXbKfyO2XDOgBH7NwlNKqPBplCjWZFsuIZiRAEWGOaQArubGNyrlXiuccjsU49lU0OhEJ5soTMPxU&state=be469fc2-b707-4413-9f14-353f69dc7e4e

 Exception Type: System.InvalidOperationException
  Exception Information: Failed to read API response
  Stack trace 
     at Sparkle.LinkedInNET.OAuth2.OAuth2Api.GetAccessToken(String authorizationCode, String redirectUri)
     at HrApp.Controllers.LinkedinController.Index(String id)

Exception Type: Sparkle.LinkedInNET.LinkedInApiException
  Exception Information: OAuth2 error (invalid_request): missing required parameters, includes an invalid parameter value, parameter more than onc

Can I get any help on this is it library problem or a problem in my code?

**Comment by sandrock** [comment]
If you have solved the issue, can you tell what is was about?

**Comment by ltoshev** [comment]
Hi

I have misinterpreted one of the parameters. 

GetAccessToken(String authorizationCode, String redirectUri) 

Since the redirect from linked in has code and state. I assumed code goes to first param and state goes to second param. But the second param should be the hardcoded URL that is set in the linkedin application. But naturally it comes to put the state there.

So it was my bad.
