### ISSUE TITLE
GetMyProfile Parameter Problem

### ISSUE THREAD

**Issue by kg-dexterity** [SparkleNetworks/LinkedInNET#10]
Hi,

What should I pass for "**acceptLanguage**" parameter inside "**GetMyProfile**" method?

```
Dim loUser As UserAuthorization = New UserAuthorization(userToken.AccessToken)
Dim profile As Person = api.Profiles.GetMyProfile(loUser, "**[acceptLanguage]**", FieldSelector.For(Of Person).WithAllFields())
```

Please assist!

**Comment by sandrock** [comment]
As you may know, one can translate his linkedin profile in different languages. This parameters is used to get the profile values in the desired language. 

You may pass a valid .NET `CultureInfo.Name` or null.

LinkedIn [recommends](https://web.archive.org/web/20140721080534/https://developer.linkedin.com/documents/profile-api) the following 6 most common values.

Language	| Header Value
--------------------|---------------
English (American)	| en-US
French	| fr-FR
German	| de-DE
Italian	| it-IT
Portuguese (Brazilian)	| pt-BR
Spanish	| es-ES

**Comment by kg-dexterity** [comment]
Thanks for the information but it does not accept null parameter. I'm passing language value like below:

```
Dim lsLanguage() As String = {"en-US"}
profile = api.Profiles.GetMyProfile(loUser, lsLanguage, FieldSelector.For(Of Person).WithFirstName().WithLastName().WithEmailAddress())
```
