### ISSUE TITLE
Only the current position is retrieved when using WithPositions()

### ISSUE THREAD

**Issue by qwert789** [SparkleNetworks/LinkedInNET#12]
I'm using this code to retrieve LinkedIn user positions:

<code>
            var api = new LinkedInApi(config);
            var user2 = new UserAuthorization(model.ExternalAccessToken);
            var profile = api.Profiles.GetMyProfile(user2, new[] { "en-US" }, FieldSelector.For<Person>().WithPositions());
</code>

However only the current position is retrieved instead of all positions, tried different config according to wiki, but it's seem that it's just not working -  i'm missing something? 

Also education return nothing and most of the configs , but in browser when using direct request everything works fine (same access token used):
https://api.linkedin.com/v1/people/~:(positions)?oauth2_access_token=TOKEN_HERE

**Comment by sandrock** [comment]
Was this a real issue? Did you fix it?

**Comment by qwert789** [comment]
It was LinkedIn limitation, to use full profile not an issue with the library
