### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by tonyyyrocks39** [SparkleNetworks/LinkedInNET#13]
What is the way to get all connections..
I have created a small asp.net application,

 var fir = profile.Connections;
                foreach (var item in fir.Person)
                {
                    var gg = item.Firstname;
                }

Here connections is always coming null,even though i get access token.
Is there any other way to get connections

**Comment by sandrock** [comment]
It looks like you are trying to list connections with the `Profiles.GetMyProfile()` method. This is not the correct way. It might work if you specify a `WithConnections()` field selector but again: this is not the correct way.

There is a [sample code](https://github.com/SparkleNetworks/LinkedInNET/blob/92bf1cdee163e380d0594f18e2dcd1fc30923549/src/NET45.Sparkle.LinkedInNET.DemoMvc5/Controllers/ExploreController.cs#L177) in the MVC demo app that show how to paginate the `Profiles.GetConnectionsByProfileId()` method.

Here is a example just for you.

```
string id = "user-id"; // from the Person.Id property
int start = 0, int count = 10;
var user = new UserAuthorization(token);
var fields = FieldSelector.For<Connections>()
    .WithDistance().WithPictureUrl()
    .WithSummary().WithLocationName().WithLocationCountryCode()
    .WithIndustry().WithId()
    .WithPublicProfileUrl()
    .WithFirstName().WithLastName().WithHeadline();

var model = api.Profiles.GetConnectionsByProfileId(user, id, start, count, fields);
```

**Comment by tonyyyrocks39** [comment]
HI sandrock,

Thanks for replying.But it seems this method does not work any more.As Linkedin changed the policies recently.It has restricted to get access to connections.

Even I have used your method it is saying access denied.

Thanks

**Comment by EmptyCoffin** [comment]
Was this looked into at all? I am experiencing the same issue when using the 
`GetConnectionsByProfileId`
On a random user, does a specific authorization scope need to be specified?

**Comment by tonyyyrocks39** [comment]
HI emptycoffin,

I have verified this earlier,As Linkedin changed the policies,we can no more access the connections.

Thanks
