### ISSUE TITLE
Profile Info doesn't give past job positions

### ISSUE THREAD

**Issue by differenz-manan** [SparkleNetworks/LinkedInNET#14]
Hi, i'm facing an issue while getting past job positions in retrieve people profile info api.

Here is my code.

`var profile = await api.Profiles.GetMyProfileAsync(user, acceptLanguages, 
                    FieldSelector.For<Person>()
                    .WithId()
                    .WithPositions()
                    .WithThreePastPositions()
                    .WithThreeCurrentPositions()
                    );`
After execution of above code, two properties of profile object ThreePastPositions and ThreeCurrentPositions returns null and Position array returns only one count. But when i have checked output from linked in rest console, it gives me 2 counts in position array and 1 count for both three past positions and three current positions.

Please help me for this problem.

Thank you.
Manan

**Comment by sandrock** [comment]
1. Is your API key authorized to get the positions? You need a special "partner" API key to do that.
2. Then, Can you compare the URL of the REST console and the URL that the library creates?

**Comment by differenz-manan** [comment]
I have checked that url for both requests are the same. 

I think it's my mistake here because it needs parner API key for getting additional profile fields.
