### ISSUE TITLE
Implement GetShare

### ISSUE THREAD

**Issue by kila03** [SparkleNetworks/LinkedInNET#17]
Hi,

First of all thanks for some great work!

Is it possible that you could implement a GetShare/GetUpdate to pick up a specific company update much similar to the current GetShares (https://developer.linkedin.com/docs/company-pages#get_update)?

**Comment by sandrock** [comment]
Hello,

Sorry for the answering delay.

For missing implementations, you can proceed with raw queries as demonstrated [here](https://github.com/SparkleNetworks/LinkedInNET/blob/79e6faaa52313cdc2a8fe8fa86da6fdd81688f44/src/NET45.Sparkle.LinkedInNET.DemoMvc5/Controllers/ExploreController.cs#L362).

You are welcome to provide an implementation. I'll keep this issue open until is implemented.

Did you do anything about this missing feature?

**Comment by sandrock** [comment]
This project is not maintained any more. Please check the README page to find alternatives.
