### ISSUE TITLE
Getting Access Token

### ISSUE THREAD

**Issue by EmptyCoffin** [SparkleNetworks/LinkedInNET#18]
Hi I am using the example in the read me but the task to get the access token never evaluates:

```              
  var redirectUrl = "http://localhost:1900/Pages/Content/LinkedIn.aspx";
  var userToken = await ApiClient.OAuth2.GetAccessTokenAsync(code, redirectUrl);
  return userToken.AccessToken;
```
![image](https://user-images.githubusercontent.com/25081459/29895495-3362aea0-8dd1-11e7-9705-ddc3d99208d3.png)
Any help is greatly appreciated

**Comment by tonyyyrocks39** [comment]
This is nothing to do with this api..this is due to deadlock situation( using async and await keyword).
Please give complete method codes

**Comment by EmptyCoffin** [comment]
Hi Tony
Thanks for the quick response. Please see below my code:
Page Load:
![image](https://user-images.githubusercontent.com/25081459/29956795-6114d010-8ee1-11e7-9b26-9edd68de450a.png)

OAuth2 method:
![image](https://user-images.githubusercontent.com/25081459/29956808-77d589ca-8ee1-11e7-993c-7835699c245f.png)

**Comment by sandrock** [comment]
For your specific project, I would like to suggest not using at all the async/await keywords.

In the OAuth2 method: remove async/await and change this line.

```
var userToken = ApiClient.OAuth2.GetAccessTokenAsync(...).Result;
```

Does it work?

**Comment by EmptyCoffin** [comment]
Unfortunately experiencing the same issues, stuck on waiting on highlighted line
![image](https://user-images.githubusercontent.com/25081459/30081773-5ec5817c-9280-11e7-912c-51585debc9bc.png)

**Comment by sandrock** [comment]
Why don't you use `GetAccessToken` instead of `GetAccessTokenAsync`?

**Comment by tonyyyrocks39** [comment]
Yes..exactly..as earlier mentioned this happens due to use of async and await..
As sandrock mentioned you need to use Getaccesstoken only.

**Comment by EmptyCoffin** [comment]
Oh opps, must of over read that. Thanks all is working now!
