### ISSUE TITLE
CompanyUpdate Field Selector

### ISSUE THREAD

**Issue by EmptyCoffin** [SparkleNetworks/LinkedInNET#19]
Hi,

I am looking at getting basic information for a company's update, I had to manually add likes as a field to get specifically as there is no `WithAllFields` extension, but I still am unable to see this information which seems available in the documentation: https://developer.linkedin.com/docs/company-pages#company_updates

Code:
![image](https://user-images.githubusercontent.com/25081459/30182524-052a8262-940f-11e7-82c9-29c894ae8e0e.png)

Trying to get the user id of the person who likes the update and how many connections they have? Any thoughts are appreciated

**Comment by sandrock** [comment]
Try to add the following fields: `.Add("likes.company").Add("likes.person")` instead of only `.Add("likes")`.

**Comment by sandrock** [comment]
Does it work?

**Comment by sandrock** [comment]
This project is not maintained any more. Please check the README page to find alternatives.
