### ISSUE TITLE
Examples would be nice

### ISSUE THREAD

**Issue by PrimeByDesign** [SparkleNetworks/LinkedInNET#21]
For those of us that are struggling with the readme markdown a set of examples would be great.

**Comment by sandrock** [comment]
It is not clear what you are struggling with. There are examples in the [Sparkle.LinkedInNET.DemoMvc5/Controllers/ExploreController.cs](https://github.com/SparkleNetworks/LinkedInNET/blob/master/src/NET45.Sparkle.LinkedInNET.DemoMvc5/Controllers/ExploreController.cs). Are those not enough?

The readme says under the [8. Explore](https://github.com/SparkleNetworks/LinkedInNET#8-explore) title that examples are given in source code. Did you miss that information?

Can you **explain** what is wrong?

**Comment by PrimeByDesign** [comment]
Hi there, sorry it's been a while since I looked at this and it's possible
that I missed your examples. I will have a look again.

Many thanks,
Kiran
