### ISSUE TITLE
Getting "Authentication failed because the remote party has closed the transport stream"

### ISSUE THREAD

**Issue by saravanan1983** [SparkleNetworks/LinkedInNET#24]
Hi,

Thanks for the  client we are using it for more than 1 year, it was working till last week.
suddenly we are getting "Authentication failed because the remote party has closed the transport stream" while getting the token, do we need to change any thing on this front.

this is the line where we are getting issue.
await api.OAuth2.GetAccessTokenAsync(code, redirectUrl)

**Comment by kenpi04** [comment]
Hi,
I have faced this issue, You can try add this line on below before call this method. 

  ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

**Comment by AlexTalcura** [comment]
We had the same issue and this fix with ServicePointManager.SecurityProtocol helped a lot!

**Comment by sandrock** [comment]
On https://developer.linkedin.com/docs we can read

> Starting 10 October 2017 developers must use TLS 1.1 or 1.2 when calling LinkedIn APIs. LinkedIn no longer supports TLS 1.0 for security reasons. 

So you shall use:

    ServicePointManager.SecurityProtocol = ServicePointManager.SecurityProtocol | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;

**Comment by sandrock** [comment]
This project is not maintained any more. Please check the README page to find alternatives.
