### ISSUE TITLE
There was an error deserializing the object of type Sparkle.LinkedInNET.OAuth2.OAuth2Error. Encountered unexpected character '<'.

### ISSUE THREAD

**Issue by kittucando** [SparkleNetworks/LinkedInNET#25]
There was an error deserializing the object of type Sparkle.LinkedInNET.OAuth2.OAuth2Error. Encountered unexpected character '<'. while calling await api.OAuth2.GetAccessTokenAsync(code, redirect_uri); method, tried with lower versions also , but the same error. Please let me know once fixed

**Comment by sandrock** [comment]
It seems the requested resource is a HTML page (unexpected '<'). Can you share the HTTP response? And the stack trace?

**Comment by israelidanny** [comment]
We're also getting the same issue.

**Comment by sandrock** [comment]
As stated in the README, this library cannot evolve to support the new LinkedIn API. 

As stated in the README, there are a few forks with live contributions. 

Please consider using [this fork](https://github.com/247GradLabs/LinkedInNET/).

Or do you confirm that you need support for this old library?

**Comment by sandrock** [comment]
I suppose you are using the new library and do not need support here. Closing.
