### ISSUE TITLE
Unable to find sparklepubliccode.pfx

### ISSUE THREAD

**Issue by MHajas97** [SparkleNetworks/LinkedInNET#26]
Error		Unable to get MD5 checksum for the key file "SparklePublicCode.pfx". Could not find file 'C:\Users\Martin\Downloads\LinkedInNET-master\src\NET35.Sparkle.LinkedInNET\SparklePublicCode.pfx'.	NET35.Sparkle.LinkedInNET

**Comment by sandrock** [comment]
What are you trying to do?

**Comment by MHajas97** [comment]
I was trying to install the NuGet package on the example code

**Comment by sandrock** [comment]
This project is not maintained any more.  Please check the project README to find alternatives.
