### ISSUE TITLE
GetAccessToken - System.InvalidOperationException: "Failed to read API response"

### ISSUE THREAD

**Issue by DanNetor** [SparkleNetworks/LinkedInNET#28]
Hi everybody,

I'm trying to get an access token using the GetAccessToken function. I keep getting the error
XmlException: Unexpected character '<'.
Can someone help me?

Best, Daniel

------------------------------------------------------------------------------------------------------------------------------
System.InvalidOperationException
  HResult=0x80131509
  Nachricht = Failed to read API response
  Quelle = Sparkle.LinkedInNET
  Stapelüberwachung:
   bei Sparkle.LinkedInNET.OAuth2.OAuth2Api.GetAccessToken(String authorizationCode, String redirectUri)
   bei LinkedInWebScrapper.WebForm1.Page_Load(Object sender, EventArgs e) in C:\VS_Local\LinkedInScrapper\LinkedInWebScrapper\WebForm1.aspx.vb: Zeile13

Innere Ausnahme 1:
SerializationException: Fehler beim Deserialisieren des Objekts "vom Typ Sparkle.LinkedInNET.OAuth2.OAuth2Error". Unerwartetes Zeichen '<'.

Innere Ausnahme 2:
XmlException: Unerwartetes Zeichen '<'.

**Comment by sandrock** [comment]
As stated in the README, this library cannot evolve to support the new LinkedIn API. 

As stated in the README, there are a few forks with live contributions. 

Please consider using [this fork](https://github.com/247GradLabs/LinkedInNET/).

Or do you confirm that you need support for this old library?

**Comment by DanNetor** [comment]
Hi @sandrock,

thanks for that information. I wasn‘t confident with V1 and V2 so i couldn‘t see the diffent. But now its clear to me. I will use the suggested fork.

best
Daniel
