### ISSUE TITLE
Asyc support?

### ISSUE THREAD

**Issue by eduardogh** [SparkleNetworks/LinkedInNET#5]
Hello,

Any plans to add async support for API operations?:

GetMyConnectionsAsync()
GetMyProfileAsync()
...

**Comment by sandrock** [comment]
Hi,

The core team has no plan for this.

However It should be easy to add this enhancement because we are using code generation. Do you think someone on your team would be ready to do it? I'm sure many users of the package would be happy to see this.

**Comment by sandrock** [comment]
It's easy I think, I'll do it.

**Comment by sandrock** [comment]
Can you @eduardogh try this package and give me feedback?

https://www.nuget.org/packages/Sparkle.LinkedInNET/1.0.9-alpha

**Comment by eduardogh** [comment]
Thank you! Async methods seems to work well. 

I use only `GetOriginalProfilePictureAsync` and `GetMyProfileAsync`. I also used `GetMyConnections` before but can't test it now per the linkedin API shutdown early this year. (If we finally get approved will test that also).

I had to reference your code directly and couldn't use the nugget package because my projects target .NET framework 4.5 (and not 4.5.1 as in the package) but that's fine.

Looking forward for the final release, (:thumbsup:)

**Comment by sandrock** [comment]
Great reply. It was a mistake to target 4.5.1, I'm not using [any related API](http://firstfloorsoftware.com/Media/DiffLists/.NET%204.5-vs-.NET%204.5.1.html). I will target 4.5 for the next release.

Do you have something else to say before I make the release?

**Comment by eduardogh** [comment]
Great, everything It's working great on my end. Thank you!
