### ISSUE TITLE
Missing Share API

### ISSUE THREAD

**Issue by collinsauve** [SparkleNetworks/LinkedInNET#7]
Hello all,

I'd like to use the [Share API](https://developer-programs.linkedin.com/documents/share-api), however it [looks like it is commented out](https://github.com/SparkleNetworks/LinkedInNET/blob/master/src/LinkedInApi.xml#L776).  Is there any reason that this can't be implemented?

**Comment by sandrock** [comment]
It looks like unfinished code.

Posting on a company profile [is implemented](https://github.com/SparkleNetworks/LinkedInNET/blob/master/src/LinkedInApi.xml#L582). Posting "as yourself" seems to use the same pattern. It looks like this should be easily to do.

Did you try anything yet?

**Comment by collinsauve** [comment]
This seems to work: 

https://github.com/SparkleNetworks/LinkedInNET/pull/8

**Comment by sandrock** [comment]
Thanks. This is now implemented with a test page in the demo web app.
