### ISSUE TITLE
Windows 10 SDK support

### ISSUE THREAD

**Issue by rafakwolf** [SparkleNetworks/LinkedInNET#9]
I'm tring to develop an application for Windows 10/Mobile.

**Comment by sandrock** [comment]
Can you be more specific on what you need and/or what is missing? A WinRT build I suppose?

Do you need just the API? Do you need the authentication helper like the one in [Facebook.Client](http://facebooksdk.net/docs/windows/login/)?

**Comment by rafakwolf** [comment]
Yes, building an app for Windows 10 Mobile

**Comment by sandrock** [comment]
I have no time nor skill to implement that. Is anyone willing to do that? [Tell me on gitter](https://gitter.im/SparkleNetworks/LinkedInNET)

**Comment by sandrock** [comment]
This project is not maintained any more. Please check the README page to find alternatives.
